In [1]:
from lxml import etree

In [2]:
import requests

In [3]:
import pymysql
import pandas as pd

In [4]:
import xml.etree.ElementTree as ET
from xml.dom.minidom import parseString

In [5]:
#网站信息
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36'}
url = "https://www.worldweatheronline.com/country.aspx"

r = requests.get(url,headers=headers)#获得服务器响应
html_code = r.content.decode(r.encoding)#解码

#print(html_code)


treeObj = etree.HTML(html_code)
#target = treeObj.xpath("//div[@class='comment-item']/div[@class='comment']/p/span[@class='short']/text()")
#target = treeObj.xpath('//div[@class="col-12 col1"]/ul/li[1]/a/div[@class="cen"]/span/text()')
#target = treeObj.xpath("//div[@class='sel_hm_country']/label/text()")
href_list = []
count = 1
while(len(href_list)<25):
    target = treeObj.xpath("//div[@class='row mt-3 bg-light rounded card-columns']/div["+str(count)+"]/@class")
    if(len(target)==1):
        href_list.append(treeObj.xpath("//div[@class='row mt-3 bg-light rounded card-columns']/div["+str(count)+"]/div[2]/ul/li/a/@href"))
    count+=1;
    




#href_list.append(treeObj.xpath("//div[@class='row mt-3 bg-light rounded card-columns']/div[1]/div[2]/ul/li/a/@href"))
#href_list.append(treeObj.xpath("//div[@class='row mt-3 bg-light rounded card-columns']/div[4]/div[2]/ul/li/a/@href"))
#target = treeObj.xpath("//div[@class='row mt-3 bg-light rounded card-columns']/div["+str(count)+"]/@class")
#res = requests.get(new_url,headers=headers)#获得服务器响应
#html_code = r.content.decode(r.encoding)#解码

#target = treeObj.xpath('//*[@id="aspnetForm"]/div[4]/main/div[2]/div[5]/div[1]/div/ul/li[1]/a/@href')


print(href_list)

[['https://www.worldweatheronline.com/afghanistan-weather.aspx', 'https://www.worldweatheronline.com/anguilla-weather.aspx', 'https://www.worldweatheronline.com/australia-weather.aspx', 'https://www.worldweatheronline.com/albania-weather.aspx', 'https://www.worldweatheronline.com/antigua-and-barbuda-weather.aspx', 'https://www.worldweatheronline.com/austria-weather.aspx', 'https://www.worldweatheronline.com/algeria-weather.aspx', 'https://www.worldweatheronline.com/argentina-weather.aspx', 'https://www.worldweatheronline.com/azerbaijan-weather.aspx', 'https://www.worldweatheronline.com/andorra-weather.aspx', 'https://www.worldweatheronline.com/armenia-weather.aspx', 'https://www.worldweatheronline.com/angola-weather.aspx', 'https://www.worldweatheronline.com/aruba-weather.aspx'], ['https://www.worldweatheronline.com/bahamas-weather.aspx', 'https://www.worldweatheronline.com/belize-weather.aspx', 'https://www.worldweatheronline.com/botswana-weather.aspx', 'https://www.worldweatheronline.com/bahrain-weather.aspx', 'https://www.worldweatheronline.com/benin-weather.aspx', 'https://www.worldweatheronline.com/brazil-weather.aspx', 'https://www.worldweatheronline.com/bangladesh-weather.aspx', 'https://www.worldweatheronline.com/bermuda-weather.aspx', 'https://www.worldweatheronline.com/brunei-darussalam-weather.aspx', 'https://www.worldweatheronline.com/barbados-weather.aspx', 'https://www.worldweatheronline.com/bhutan-weather.aspx', 'https://www.worldweatheronline.com/bulgaria-weather.aspx', 'https://www.worldweatheronline.com/belarus-weather.aspx', 'https://www.worldweatheronline.com/bolivia-weather.aspx', 'https://www.worldweatheronline.com/burkina-faso-weather.aspx', 'https://www.worldweatheronline.com/belgium-weather.aspx', 'https://www.worldweatheronline.com/bosnia-and-herzegovina-weather.aspx', 'https://www.worldweatheronline.com/burundi-weather.aspx'], ['https://www.worldweatheronline.com/cambodia-weather.aspx', 'https://www.worldweatheronline.com/chile-weather.aspx', 'https://www.worldweatheronline.com/cook-island-weather.aspx', 'https://www.worldweatheronline.com/cameroon-weather.aspx', 'https://www.worldweatheronline.com/china-weather.aspx', 'https://www.worldweatheronline.com/costa-rica-weather.aspx', 'https://www.worldweatheronline.com/canada-weather.aspx', 'https://www.worldweatheronline.com/christmas-island-weather.aspx', 'https://www.worldweatheronline.com/cote-divoire-weather.aspx', 'https://www.worldweatheronline.com/cape-verde-weather.aspx', 'https://www.worldweatheronline.com/cocos-keeling-islands-weather.aspx', 'https://www.worldweatheronline.com/croatia-weather.aspx', 'https://www.worldweatheronline.com/cayman-islands-weather.aspx', 'https://www.worldweatheronline.com/colombia-weather.aspx', 'https://www.worldweatheronline.com/cuba-weather.aspx', 'https://www.worldweatheronline.com/central-african-republic-weather.aspx', 'https://www.worldweatheronline.com/comoros-weather.aspx', 'https://www.worldweatheronline.com/cyprus-weather.aspx', 'https://www.worldweatheronline.com/chad-weather.aspx', 'https://www.worldweatheronline.com/congo-weather.aspx', 'https://www.worldweatheronline.com/czech-republic-weather.aspx'], ['https://www.worldweatheronline.com/democratic-republic-of-congo-weather.aspx', 'https://www.worldweatheronline.com/djibouti-weather.aspx', 'https://www.worldweatheronline.com/dominican-republic-weather.aspx', 'https://www.worldweatheronline.com/denmark-weather.aspx', 'https://www.worldweatheronline.com/dominica-weather.aspx'], ['https://www.worldweatheronline.com/ecuador-weather.aspx', 'https://www.worldweatheronline.com/equatorial-guinea-weather.aspx', 'https://www.worldweatheronline.com/ethiopia-weather.aspx', 'https://www.worldweatheronline.com/egypt-weather.aspx', 'https://www.worldweatheronline.com/eritrea-weather.aspx', 'https://www.worldweatheronline.com/el-salvador-weather.aspx', 'https://www.worldweatheronline.com/estonia-weather.aspx'], ['https://www.worldweatheronline.com/falkland-islands-weather.aspx', 'https://www.worldweatheronline.com/finland-weather.aspx', 'https://www.worldweatheronline.com/french-polynesia-islands-weather.aspx', 'https://www.worldweatheronline.com/faroe-islands-weather.aspx', 'https://www.worldweatheronline.com/france-weather.aspx', 'https://www.worldweatheronline.com/french-southern-and-antarctic-lands-weather.aspx', 'https://www.worldweatheronline.com/fiji-islands-weather.aspx', 'https://www.worldweatheronline.com/french-guiana-weather.aspx'], ['https://www.worldweatheronline.com/gabon-weather.aspx', 'https://www.worldweatheronline.com/gibraltar-weather.aspx', 'https://www.worldweatheronline.com/guatemala-weather.aspx', 'https://www.worldweatheronline.com/gambia-weather.aspx', 'https://www.worldweatheronline.com/greece-weather.aspx', 'https://www.worldweatheronline.com/guernsey-weather.aspx', 'https://www.worldweatheronline.com/georgia-weather.aspx', 'https://www.worldweatheronline.com/greenland-weather.aspx', 'https://www.worldweatheronline.com/guinea-weather.aspx', 'https://www.worldweatheronline.com/germany-weather.aspx', 'https://www.worldweatheronline.com/grenada-weather.aspx', 'https://www.worldweatheronline.com/guinea-bissau-weather.aspx', 'https://www.worldweatheronline.com/ghana-weather.aspx', 'https://www.worldweatheronline.com/guadeloupe-weather.aspx', 'https://www.worldweatheronline.com/guyana-weather.aspx'], ['https://www.worldweatheronline.com/haiti-weather.aspx', 'https://www.worldweatheronline.com/hong-kong-weather.aspx', 'https://www.worldweatheronline.com/honduras-weather.aspx', 'https://www.worldweatheronline.com/hungary-weather.aspx'], ['https://www.worldweatheronline.com/iceland-weather.aspx', 'https://www.worldweatheronline.com/iran-weather.aspx', 'https://www.worldweatheronline.com/isle-of-man-weather.aspx', 'https://www.worldweatheronline.com/india-weather.aspx', 'https://www.worldweatheronline.com/iraq-weather.aspx', 'https://www.worldweatheronline.com/israel-weather.aspx', 'https://www.worldweatheronline.com/indonesia-weather.aspx', 'https://www.worldweatheronline.com/ireland-weather.aspx', 'https://www.worldweatheronline.com/italy-weather.aspx'], ['https://www.worldweatheronline.com/jamaica-weather.aspx', 'https://www.worldweatheronline.com/jersey-weather.aspx', 'https://www.worldweatheronline.com/japan-weather.aspx', 'https://www.worldweatheronline.com/jordan-weather.aspx'], ['https://www.worldweatheronline.com/kazakhstan-weather.aspx', 'https://www.worldweatheronline.com/kiribati-weather.aspx', 'https://www.worldweatheronline.com/kuwait-weather.aspx', 'https://www.worldweatheronline.com/kenya-weather.aspx', 'https://www.worldweatheronline.com/kosovo-weather.aspx', 'https://www.worldweatheronline.com/kyrghyzstan-weather.aspx'], ['https://www.worldweatheronline.com/lao-peoples-democratic-republic-weather.aspx', 'https://www.worldweatheronline.com/lesotho-weather.aspx', 'https://www.worldweatheronline.com/liechtenstein-weather.aspx', 'https://www.worldweatheronline.com/latvia-weather.aspx', 'https://www.worldweatheronline.com/liberia-weather.aspx', 'https://www.worldweatheronline.com/lithuania-weather.aspx', 'https://www.worldweatheronline.com/lebanon-weather.aspx', 'https://www.worldweatheronline.com/libya-weather.aspx', 'https://www.worldweatheronline.com/luxembourg-weather.aspx'], ['https://www.worldweatheronline.com/macau-weather.aspx', 'https://www.worldweatheronline.com/marshall-islands-weather.aspx', 'https://www.worldweatheronline.com/monaco-weather.aspx', 'https://www.worldweatheronline.com/macedonia-weather.aspx', 'https://www.worldweatheronline.com/martinique-weather.aspx', 'https://www.worldweatheronline.com/mongolia-weather.aspx', 'https://www.worldweatheronline.com/madagascar-weather.aspx', 'https://www.worldweatheronline.com/mauritania-weather.aspx', 'https://www.worldweatheronline.com/montenegro-weather.aspx', 'https://www.worldweatheronline.com/malawi-weather.aspx', 'https://www.worldweatheronline.com/mauritius-weather.aspx', 'https://www.worldweatheronline.com/montserrat-weather.aspx', 'https://www.worldweatheronline.com/malaysia-weather.aspx', 'https://www.worldweatheronline.com/mayotte-weather.aspx', 'https://www.worldweatheronline.com/morocco-weather.aspx', 'https://www.worldweatheronline.com/maldives-weather.aspx', 'https://www.worldweatheronline.com/mexico-weather.aspx', 'https://www.worldweatheronline.com/mozambique-weather.aspx', 'https://www.worldweatheronline.com/mali-weather.aspx', 'https://www.worldweatheronline.com/micronesia-weather.aspx', 'https://www.worldweatheronline.com/myanmar-weather.aspx', 'https://www.worldweatheronline.com/malta-weather.aspx', 'https://www.worldweatheronline.com/moldova-weather.aspx'], ['https://www.worldweatheronline.com/namibia-weather.aspx', 'https://www.worldweatheronline.com/new-caledonia-weather.aspx', 'https://www.worldweatheronline.com/niue-weather.aspx', 'https://www.worldweatheronline.com/nauru-island-weather.aspx', 'https://www.worldweatheronline.com/new-zealand-weather.aspx', 'https://www.worldweatheronline.com/norfolk-island-weather.aspx', 'https://www.worldweatheronline.com/nepal-weather.aspx', 'https://www.worldweatheronline.com/nicaragua-weather.aspx', 'https://www.worldweatheronline.com/north-korea-weather.aspx', 'https://www.worldweatheronline.com/netherlands-weather.aspx', 'https://www.worldweatheronline.com/niger-weather.aspx', 'https://www.worldweatheronline.com/northern-mariana-islands-weather.aspx', 'https://www.worldweatheronline.com/netherlands-antilles-weather.aspx', 'https://www.worldweatheronline.com/nigeria-weather.aspx', 'https://www.worldweatheronline.com/norway-weather.aspx'], ['https://www.worldweatheronline.com/oman-weather.aspx'], ['https://www.worldweatheronline.com/pakistan-weather.aspx', 'https://www.worldweatheronline.com/papua-new-guinea-weather.aspx', 'https://www.worldweatheronline.com/pitcairn-island-weather.aspx', 'https://www.worldweatheronline.com/palau-weather.aspx', 'https://www.worldweatheronline.com/paraguay-weather.aspx', 'https://www.worldweatheronline.com/poland-weather.aspx', 'https://www.worldweatheronline.com/palestine-weather.aspx', 'https://www.worldweatheronline.com/peru-weather.aspx', 'https://www.worldweatheronline.com/portugal-weather.aspx', 'https://www.worldweatheronline.com/panama-weather.aspx', 'https://www.worldweatheronline.com/philippines-weather.aspx'], ['https://www.worldweatheronline.com/qatar-weather.aspx'], ['https://www.worldweatheronline.com/reunion-and-associated-islands-weather.aspx', 'https://www.worldweatheronline.com/russia-weather.aspx', 'https://www.worldweatheronline.com/romania-weather.aspx', 'https://www.worldweatheronline.com/rwanda-weather.aspx'], ['https://www.worldweatheronline.com/saint-helena-weather.aspx', 'https://www.worldweatheronline.com/serbia-weather.aspx', 'https://www.worldweatheronline.com/south-korea-weather.aspx', 'https://www.worldweatheronline.com/saint-kitts-and-nevis-weather.aspx', 'https://www.worldweatheronline.com/seychelles-islands-weather.aspx', 'https://www.worldweatheronline.com/spain-weather.aspx', 'https://www.worldweatheronline.com/saint-lucia-weather.aspx', 'https://www.worldweatheronline.com/sierra-leone-weather.aspx', 'https://www.worldweatheronline.com/sri-lanka-weather.aspx', 'https://www.worldweatheronline.com/saint-pierre-and-miquelon-weather.aspx', 'https://www.worldweatheronline.com/singapore-weather.aspx', 'https://www.worldweatheronline.com/sudan-weather.aspx', 'https://www.worldweatheronline.com/saint-vincent-and-the-grenadines-weather.aspx', 'https://www.worldweatheronline.com/slovakia-weather.aspx', 'https://www.worldweatheronline.com/suriname-weather.aspx', 'https://www.worldweatheronline.com/samoa-weather.aspx', 'https://www.worldweatheronline.com/slovenia-weather.aspx', 'https://www.worldweatheronline.com/swaziland-weather.aspx', 'https://www.worldweatheronline.com/san-marino-weather.aspx', 'https://www.worldweatheronline.com/solomon-islands-weather.aspx', 'https://www.worldweatheronline.com/sweden-weather.aspx', 'https://www.worldweatheronline.com/sao-tome-and-principe-weather.aspx', 'https://www.worldweatheronline.com/somalia-weather.aspx', 'https://www.worldweatheronline.com/switzerland-weather.aspx', 'https://www.worldweatheronline.com/saudi-arabia-weather.aspx', 'https://www.worldweatheronline.com/south-africa-weather.aspx', 'https://www.worldweatheronline.com/syria-weather.aspx', 'https://www.worldweatheronline.com/senegal-weather.aspx', 'https://www.worldweatheronline.com/south-georgia-and-south-sandwich-islands-weather.aspx'], ['https://www.worldweatheronline.com/taiwan-weather.aspx', 'https://www.worldweatheronline.com/tokelau-islands-weather.aspx', 'https://www.worldweatheronline.com/turkmenistan-weather.aspx', 'https://www.worldweatheronline.com/tajikistan-weather.aspx', 'https://www.worldweatheronline.com/tonga-weather.aspx', 'https://www.worldweatheronline.com/turks-and-caicos-islands-weather.aspx', 'https://www.worldweatheronline.com/tanzania-weather.aspx', 'https://www.worldweatheronline.com/trinidad-and-tobago-weather.aspx', 'https://www.worldweatheronline.com/tuvalu-weather.aspx', 'https://www.worldweatheronline.com/thailand-weather.aspx', 'https://www.worldweatheronline.com/tunisia-weather.aspx', 'https://www.worldweatheronline.com/togo-weather.aspx', 'https://www.worldweatheronline.com/turkey-weather.aspx'], ['https://www.worldweatheronline.com/uganda-weather.aspx', 'https://www.worldweatheronline.com/united-kingdom-weather.aspx', 'https://www.worldweatheronline.com/uzbekistan-weather.aspx', 'https://www.worldweatheronline.com/ukraine-weather.aspx', 'https://www.worldweatheronline.com/united-states-of-america-weather.aspx', 'https://www.worldweatheronline.com/united-arab-emirates-weather.aspx', 'https://www.worldweatheronline.com/uruguay-weather.aspx'], ['https://www.worldweatheronline.com/vanuatu-weather.aspx', 'https://www.worldweatheronline.com/venezuela-weather.aspx', 'https://www.worldweatheronline.com/virgin-islands-weather.aspx', 'https://www.worldweatheronline.com/vatican-city-weather.aspx', 'https://www.worldweatheronline.com/vietnam-weather.aspx'], ['https://www.worldweatheronline.com/wallis-and-futuna-islands-weather.aspx', 'https://www.worldweatheronline.com/western-sahara-weather.aspx'], ['https://www.worldweatheronline.com/yemen-weather.aspx'], ['https://www.worldweatheronline.com/zambia-weather.aspx', 'https://www.worldweatheronline.com/zimbabwe-weather.aspx']]

In [6]:
#国家名字
country_list = []
count = 1
while(len(country_list)<25):
    target = treeObj.xpath("//div[@class='row mt-3 bg-light rounded card-columns']/div["+str(count)+"]/@class")
    if(len(target)==1):
        country_list.append(treeObj.xpath("//div[@class='row mt-3 bg-light rounded card-columns']/div["+str(count)+"]/div[2]/ul/li/a/text()"))
    count+=1;
    
print(country_list)

[['Afghanistan', 'Anguilla', 'Australia', 'Albania', 'Antigua And Barb...', 'Austria', 'Algeria', 'Argentina', 'Azerbaijan', 'Andorra', 'Armenia', 'Angola', 'Aruba'], ['Bahamas', 'Belize', 'Botswana', 'Bahrain', 'Benin', 'Brazil', 'Bangladesh', 'Bermuda', 'Brunei Darussala...', 'Barbados', 'Bhutan', 'Bulgaria', 'Belarus', 'Bolivia', 'Burkina Faso', 'Belgium', 'Bosnia And Herze...', 'Burundi'], ['Cambodia', 'Chile', 'Cook Island', 'Cameroon', 'China', 'Costa Rica', 'Canada', 'Christmas Island', "Cote D'ivoire", 'Cape Verde', 'Cocos (Keeling) ...', 'Croatia', 'Cayman Islands', 'Colombia', 'Cuba', 'Central African ...', 'Comoros', 'Cyprus', 'Chad', 'Congo', 'Czech Republic'], ['Democratic Repub...', 'Djibouti', 'Dominican Republ...', 'Denmark', 'Dominica'], ['Ecuador', 'Equatorial Guine...', 'Ethiopia', 'Egypt', 'Eritrea', 'El Salvador', 'Estonia'], ['Falkland Islands', 'Finland', 'French Polynesia...', 'Faroe Islands', 'France', 'French Southern ...', 'Fiji Islands', 'French Guiana'], ['Gabon', 'Gibraltar', 'Guatemala', 'Gambia', 'Greece', 'Guernsey', 'Georgia', 'Greenland', 'Guinea', 'Germany', 'Grenada', 'Guinea-Bissau', 'Ghana', 'Guadeloupe', 'Guyana'], ['Haiti', 'Hong Kong', 'Honduras', 'Hungary'], ['Iceland', 'Iran', 'Isle Of Man', 'India', 'Iraq', 'Israel', 'Indonesia', 'Ireland', 'Italy'], ['Jamaica', 'Jersey', 'Japan', 'Jordan'], ['Kazakhstan', 'Kiribati', 'Kuwait', 'Kenya', 'Kosovo', 'Kyrghyzstan'], ["Lao People's Dem...", 'Lesotho', 'Liechtenstein', 'Latvia', 'Liberia', 'Lithuania', 'Lebanon', 'Libya', 'Luxembourg'], ['Macau', 'Marshall Islands', 'Monaco', 'Macedonia', 'Martinique', 'Mongolia', 'Madagascar', 'Mauritania', 'Montenegro', 'Malawi', 'Mauritius', 'Montserrat', 'Malaysia', 'Mayotte', 'Morocco', 'Maldives', 'Mexico', 'Mozambique', 'Mali', 'Micronesia', 'Myanmar', 'Malta', 'Moldova'], ['Namibia', 'New Caledonia', 'Niue', 'Nauru Island', 'New Zealand', 'Norfolk Island', 'Nepal', 'Nicaragua', 'North Korea', 'Netherlands', 'Niger', 'Northern Mariana...', 'Netherlands Anti...', 'Nigeria', 'Norway'], ['Oman'], ['Pakistan', 'Papua New Guinea', 'Pitcairn Island', 'Palau', 'Paraguay', 'Poland', 'Palestine', 'Peru', 'Portugal', 'Panama', 'Philippines'], ['Qatar'], ['Reunion And Asso...', 'Russia', 'Romania', 'Rwanda'], ['Saint Helena', 'Serbia', 'South Korea', 'Saint Kitts And ...', 'Seychelles Islan...', 'Spain', 'Saint Lucia', 'Sierra Leone', 'Sri Lanka', 'Saint Pierre And...', 'Singapore', 'Sudan', 'Saint Vincent An...', 'Slovakia', 'Suriname', 'Samoa', 'Slovenia', 'Swaziland', 'San Marino', 'Solomon Islands', 'Sweden', 'Sao Tome And Pri...', 'Somalia', 'Switzerland', 'Saudi Arabia', 'South Africa', 'Syria', 'Senegal', 'South Georgia An...'], ['Taiwan', 'Tokelau Islands', 'Turkmenistan', 'Tajikistan', 'Tonga', 'Turks And Caicos...', 'Tanzania', 'Trinidad And Tob...', 'Tuvalu', 'Thailand', 'Tunisia', 'Togo', 'Turkey'], ['Uganda', 'United Kingdom', 'Uzbekistan', 'Ukraine', 'United States Of...', 'United Arab Emir...', 'Uruguay'], ['Vanuatu', 'Venezuela', 'Virgin Islands', 'Vatican City', 'Vietnam'], ['Wallis And Futun...', 'Western Sahara'], ['Yemen'], ['Zambia', 'Zimbabwe']]

In [ ]:
# initialise country name
# 连接mysql
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(country_list)):
    for y in range(len(country_list[x])):
        sql = "insert into country(country_name)values('%s')" %(country_list[x][y])
        if(country_list[x][y]=='Cote D\'ivoire'):
            sql = "insert into country(country_name)values('Cote D\''ivoire')"
        if(country_list[x][y]=='Lao People\'s Dem...'):
            sql = "insert into country(country_name)values('Lao People\''s Dem...')"
        #sql="insert into country (country_name) values ('"+str(country_list[x][y])+"')"
        #利用pandas直接获取数据
        #第四部：执行sql语句
        cursor.execute(sql)
        # ！！！！！！！数据提交 commit()  ,不提交数据库没有信息
        conn.commit()
# sql="insert into country (country_name) values ('"+str(country_list[0][0])+"')";
# cursor = conn.cursor()
# cursor.execute(sql)
# conn.commit()
#关闭游标
cursor.close()
#关闭数据库
conn.close()

In [ ]:
#cities list
result = []
for x in href_list[8]:
    r = requests.get(x,headers=headers)#获得服务器响应
    html_code = r.content.decode(r.encoding)#解码

    #print(html_code)
    
    treeObj = etree.HTML(html_code)
    result.append(treeObj.xpath('//*[@id="aspnetForm"]/div[4]/main/div[2]/div[5]/div[1]/div/ul/li/a/text()'))
print(result)

In [ ]:
#Country A
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x, result[x][y])
        if(result[x][y]=='Saint Mary\'s'):
            sql = "insert into city(country_id, city_name)values("+str(x)+", 'Saint Mary\''s')"
        if(result[x][y]=='L\'aldosa'):
            sql = "insert into city(country_id, city_name)values("+str(x)+", 'L\''aldosa')"
        cursor.execute(sql)
        conn.commit()
cursor.close()

conn.close()

In [ ]:
#Country B
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+13, result[x][y])
        if(result[x][y]=='\'Ain-Ad-Dar'):
            sql = "insert into city(country_id, city_name)values("+str(x+13)+", '\''Ain-Ad-Dar')"
        if(result[x][y]=='Flatt\'s Village'):
            sql = "insert into city(country_id, city_name)values("+str(x+13)+", 'Flatt\''s Village')"
        if(result[x][y]=='Tucker\'s Town'):
            sql = "insert into city(country_id, city_name)values("+str(x+13)+", 'Tucker\''s Town')"
        if(result[x][y]=='Saint George\'s Tow...'):
            sql = "insert into city(country_id, city_name)values("+str(x+13)+", 'Saint George\''s Tow...')"            
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country C
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+31, result[x][y])
        if(result[x][y]=='N\'djamena'):
            sql = "insert into city(country_id, city_name)values("+str(x+31)+", 'N\''djamena')"
        if(result[x][y]=='N\'guiri'):
            sql = "insert into city(country_id, city_name)values("+str(x+31)+", 'N\''guiri')"           
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country D
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+52, result[x][y])
        if(result[x][y]=='Poste D\' Anghor'):
            sql = "insert into city(country_id, city_name)values("+str(x+52)+", 'Poste D\'' Anghor')"
        if(result[x][y]=='Boul\'aos'):
            sql = "insert into city(country_id, city_name)values("+str(x+52)+", 'Boul\''aos')"           
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country E
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+57, result[x][y])
        if(result[x][y]=='Aya\'bivila'):
            sql = "insert into city(country_id, city_name)values("+str(x+57)+", 'Aya\''bivila')"
        if(result[x][y]=='Aya\'kue'):
            sql = "insert into city(country_id, city_name)values("+str(x+57)+", 'Aya\''kue')"
        if(result[x][y]=='Aya\'ntang'):
            sql = "insert into city(country_id, city_name)values("+str(x+57)+", 'Aya\''ntang')"
        if(result[x][y]=='Ase\'sok'):
            sql = "insert into city(country_id, city_name)values("+str(x+57)+", 'Ase\''sok')"
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country F
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+64, result[x][y])

        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country G
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+72, result[x][y])
        if(result[x][y]=='Tqvarch\'eli'):
            sql = "insert into city(country_id, city_name)values("+str(x+72)+", 'Tqvarch\''eli')"
        if(result[x][y]=='L\'esterre'):
            sql = "insert into city(country_id, city_name)values("+str(x+72)+", 'L\''esterre')"
        if(result[x][y]=='Saint George\'s'):
            sql = "insert into city(country_id, city_name)values("+str(x+72)+", 'Saint George\''s')"
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country H
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+87, result[x][y])
        if(result[x][y]=='Ch\'uan-Wan'):
            sql = "insert into city(country_id, city_name)values("+str(x+87)+", 'Ch\''uan-Wan')"
        if(result[x][y]=='Ch\'ang-Sha'):
            sql = "insert into city(country_id, city_name)values("+str(x+87)+", 'Ch\''ang-Sha')"
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country I
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+91, result[x][y])
        if(result[x][y]=='Reggio Nell\'emilia'):
            sql = "insert into city(country_id, city_name)values("+str(x+91)+", 'Reggio Nell\''emilia')"
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country J
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+100, result[x][y])
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country K
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+104, result[x][y])
        if(result[x][y]=='Ad Dasma\''):
            sql = "insert into city(country_id, city_name)values("+str(x+104)+", 'Ad Dasma\''')"
        if(result[x][y]=='(( Ketmen\'tebe ))'):
            sql = "insert into city(country_id, city_name)values("+str(x+104)+", '(( Ketmen\''tebe ))')"
        if(result[x][y]=='(( Kodul\' ))'):
            sql = "insert into city(country_id, city_name)values("+str(x+104)+", '(( Kodul\'' ))')"
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country L
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+110, result[x][y])
        if(result[x][y]=='Al Bayda\''):
            sql = "insert into city(country_id, city_name)values("+str(x+110)+", 'Al Bayda\''')"
        if(result[x][y]=='Al Khala\'ifah'):
            sql = "insert into city(country_id, city_name)values("+str(x+110)+", 'Al Khala\''ifah')"
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country M
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+119, result[x][y])
        if(result[x][y]=='Lin-Chia-Ts\'un'):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Lin-Chia-Ts\''un')"
        if(result[x][y]=='Ts\'ao-Chia-Ts\'un'):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Ts\''ao-Chia-Ts\''un')"
        if(result[x][y]=='Anses D\'arlets'):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Anses D\''arlets')"
        if(result[x][y]=='Anses D\'arlet'):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Anses D\''arlet')"
        if(result[x][y]=='Saint Peter\'s Vill...'):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Saint Peter\''s Vill...')"
        if(result[x][y]=='Gerald\'s'):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Gerald\''s')"
        if(result[x][y]=='Trant\'s'):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Lin-Chia-Ts\''un')"
        if(result[x][y]=='Hodge\'s Hill'):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Hodge\''s Hill')"
        if(result[x][y]=='Tuitt\'s'):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Tuitt\''s')"
        if(result[x][y]=='Lee\'s'):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Lee\''s')"
        if(result[x][y]=='Saint George\'s Hil...'):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Saint George\''s Hil...')"
        if(result[x][y]=='Saint John\'s'):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Saint John\''s')"
        if(result[x][y]=='Saint John\'s Villa...'):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Saint John\''s Villa...')"
        if(result[x][y]=='U\'ngoofaaru'):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'U\''ngoofaaru')"
        if(result[x][y]=='Adibuwe\''):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Adibuwe\''')"
        if(result[x][y]=='Adubuwe\''):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Adubuwe\''')"
        if(result[x][y]=='Baleabaat\''):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Baleabaat\''')"
        if(result[x][y]=='Balebat\''):
            sql = "insert into city(country_id, city_name)values("+str(x+119)+", 'Balebat\''')"
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country N
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+142, result[x][y])
        if(result[x][y]=='\'S-Hertogenbosch'):
            sql = "insert into city(country_id, city_name)values("+str(x+142)+", '\''S-Hertogenbosch')"
        if(result[x][y]=='Bou\'i Seru'):
            sql = "insert into city(country_id, city_name)values("+str(x+142)+", 'Bou\''i Seru')"
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country O
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+157, result[x][y])
        if(result[x][y]=='Fu\'ad Al Hadu'):
            sql = "insert into city(country_id, city_name)values("+str(x+157)+", 'Fu\''ad Al Hadu')"
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country P
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+158, result[x][y])
        if(result[x][y]=='Al Fasa\'il'):
            sql = "insert into city(country_id, city_name)values("+str(x+158)+", 'Al Fasa\''il')"
        if(result[x][y]=='\'Arrabuna'):
            sql = "insert into city(country_id, city_name)values("+str(x+158)+", '\''Arrabuna')"
        if(result[x][y]=='\'Ofarim'):
            sql = "insert into city(country_id, city_name)values("+str(x+158)+", '\''Ofarim')"
        if(result[x][y]=='\'Omarim'):
            sql = "insert into city(country_id, city_name)values("+str(x+158)+", '\''Omarim')"
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country Q
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+169, result[x][y])
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country R
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+170, result[x][y])
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country S
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+174, result[x][y])
        if(result[x][y]=='Fothergill\'s'):
            sql = "insert into city(country_id, city_name)values("+str(x+174)+", 'Fothergill\''s')"
        if(result[x][y]=='Buck\'s Hill'):
            sql = "insert into city(country_id, city_name)values("+str(x+174)+", 'Buck\''s Hill')"
        if(result[x][y]=='Webb\'s Ground'):
            sql = "insert into city(country_id, city_name)values("+str(x+174)+", 'Webb\''s Ground')"
        if(result[x][y]=='L\'esperance'):
            sql = "insert into city(country_id, city_name)values("+str(x+174)+", 'L\''esperance')"
        if(result[x][y]=='L\'hospitalet De Ll...'):
            sql = "insert into city(country_id, city_name)values("+str(x+174)+", 'L\''hospitalet De Ll...')"
        if(result[x][y]=='Fond D\'or'):
            sql = "insert into city(country_id, city_name)values("+str(x+174)+", 'Fond D\''or')"
        if(result[x][y]=='Aena\'aiwasi'):
            sql = "insert into city(country_id, city_name)values("+str(x+174)+", 'Aena\''aiwasi')"
        if(result[x][y]=='A\'ama'):
            sql = "insert into city(country_id, city_name)values("+str(x+174)+", 'A\''ama')"
        if(result[x][y]=='A\'arai'):
            sql = "insert into city(country_id, city_name)values("+str(x+174)+", 'A\''arai')"
        if(result[x][y]=='Ahe\'ohia'):
            sql = "insert into city(country_id, city_name)values("+str(x+174)+", 'Ahe\''ohia')"
        if(result[x][y]=='Abira\'adoa'):
            sql = "insert into city(country_id, city_name)values("+str(x+174)+", 'Abira\''adoa')"
        if(result[x][y]=='Ae\'akwato'):
            sql = "insert into city(country_id, city_name)values("+str(x+174)+", 'Ae\''akwato')"
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country T
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+203, result[x][y])
        if(result[x][y]=='Vos\'moye Marta'):
            sql = "insert into city(country_id, city_name)values("+str(x+203)+", 'Vos\''moye Marta')"
        if(result[x][y]=='Nuku\'alofa'):
            sql = "insert into city(country_id, city_name)values("+str(x+203)+", 'Nuku\''alofa')"
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country U
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+216, result[x][y])
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country V
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+223, result[x][y])
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country W
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+228, result[x][y])
        if(result[x][y]=='Mata\'utu'):
            sql = "insert into city(country_id, city_name)values("+str(x+228)+", 'Mata\''utu')"
        if(result[x][y]=='Ha\'alalo'):
            sql = "insert into city(country_id, city_name)values("+str(x+228)+", 'Ha\''alalo')"
        if(result[x][y]=='La\'youn'):
            sql = "insert into city(country_id, city_name)values("+str(x+228)+", 'La\''youn')"
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country Y
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+230, result[x][y])
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [ ]:
#Country Z
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()


for x in range(len(result)):
    for y in range(len(result[x])):
        sql = "insert into city(country_id, city_name)values(%s, '%s')" %(x+231, result[x][y])
        cursor.execute(sql)
        conn.commit()
cursor.close()
conn.close()

In [7]:
def xmlFind(city, country):
    city = normalize(city)
    country = normalize(country)
    pid = pidFind(city, country)
    city= city.replace(' ','+')
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36'}
    url = 'https://www.worldweatheronline.com/v2/meteogram.ashx?pid='+str(pid)+'&city='+str(city)+'%2c+'+str(country)
    r = requests.get(url,headers=headers)#获得服务器响应
    html_code = r.content.decode(r.encoding)#解码
    root = ET.fromstring(html_code)
    return root[1][0][0][0].attrib['name']

In [8]:
def pidFind(city, country):
    country = country.replace(" ","-")
    city = city.replace(" ","-")
    url_country='https://www.worldweatheronline.com/'+str(country)+'-weather.aspx'
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36'}
    r = requests.get(url_country,headers=headers)#获得服务器响应
    html_code = r.content.decode(r.encoding)#解码

    #print(html_code)
    
    treeObj = etree.HTML(html_code)
    l = (treeObj.xpath('//*[@id="aspnetForm"]/div[4]/main/div[2]/div[5]/div[1]/div/ul/li/a/@href'))
    if(len(l)==0):
        l = (treeObj.xpath('//*[@id="aspnetForm"]/div[4]/main/div[2]/div[4]/div[1]/div/ul/li/a/@href'))
    city = city.lower()
    for i in l:
        if(city in i):
            url_city = i
    r = requests.get(url_city,headers=headers)#获得服务器响应
    html_code = r.content.decode(r.encoding)#解码
    treeObj = etree.HTML(html_code)
    result = treeObj.xpath('//*[@id="ctl00_areaid"]/@value')[0]
    return result

In [10]:
def normalize(s):
    s = s.replace('\'', '')
    s = s.replace('`','')
    return s

In [11]:
xmlFind("Ottawa", "Canada")

'Partly cloudy'

In [12]:
pidFind("Ottawa", "Canada")

'42059'

In [ ]:
#from db get city name and coutry name
conn = pymysql.connect(host='localhost', user='root',password='wxp997925',
                       database='weather',charset="utf8")
cursor = conn.cursor()

city_id = 1

weather_list = []

while(city_id <= 8149):
    sql_country_id = "select country_id from city where city_id=" + str(city_id)
    cursor.execute(sql_country_id)
    country_id = cursor.fetchone()[0] + 1
    sql_country = "select country_name from country where country_id=" + str(country_id)
    cursor.execute(sql_country)
    country = cursor.fetchone()[0]
    sql_city = "select city_name from city where city_id=" + str(city_id)
    cursor.execute(sql_city)
    city = cursor.fetchone()[0]
    print(city)
    print(country)
    weather = xmlFind(city, country)
    print(weather)
    #sql = "select current_weather from city where city_id=" + str(city_id)
    #cursor.execute(sql)
    #weather = cursor.fetchone()[0]
    weather_list.append(weather)
    city_id += 1


print(weather_list)
cursor.close()
conn.close()